spring:
  application:
    name: learning-progress-management

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          show_sql: true
          format_sql: true
          generate_statistics: false
          jdbc.batch_size: 500
          order_inserts: true
          order_updates: true

  liquibase:
    enabled: false
  jackson:
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
    time-zone: GMT+7
  zipkin:
    enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

server:
  port: 8080
  shutdown: graceful
  tomcat:
    threads:
      max: 500
      min-spare: 20
    max-connections: 500
    accept-count: 200
    max-http-form-post-size: 10MB
  servlet:
    context-path: /learning-progress-management

jwt:
  secret: ${JWT_SECRET}
  expiration: 7200000

logging:
  level:
    ROOT: INFO
    com.apus.base: INFO
    org.hibernate.sql: WARN
    org.hibernate.type: WARN
    org.springframework.orm.jpa: WARN
    org.springframework.transaction: WARN
    org.hibernate.engine.transaction.internal.TransactionImpl: WARN

mapping:
  max-message-per-sub-batch: 1000
