package com.learning.progress.common;

public enum ActionType {
    CREATE, UPDATE, DELETE, JOIN, CREATE_CLASS, UPDATE_CLASS, TOGGLE_CLASS_ACTIVATION, DELETE_CLASS, DELETE_CHAPTER, UPDATE_CHAPTER, CREATE_CHAPTER, DELETE_LESSON, UPDATE_LESSON, CREATE_LESSON, LEAVE
}
